language: python
sudo: required
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements_dev.txt
  - pip install pytest-cov codecov
  - pip install -e .
script:
  - pytest --cov
after_success:
  - codecov
